vich_uploader:
    db_driver: orm

    mappings:
        evenement_image:
            uri_prefix: '%app.path.featured_evenement_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.featured_evenement_images%'
<<<<<<< Updated upstream
        evenement_vignette:
            uri_prefix: '%app.path.featured_evenement_vignettes%'
            upload_destination: '%kernel.project_dir%/public%app.path.featured_evenement_vignettes%'
=======
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        evenement_vignette:
            uri_prefix: '%app.path.featured_evenement_vignettes%'
            upload_destination: '%kernel.project_dir%/public%app.path.featured_evenement_vignettes%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
>>>>>>> Stashed changes
